config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  post 'mail', to: 'mail#receive', as: :receive_mail

  get 'pages/home'
  get 'pages/index'
  get 'pages/imprint'
  get 'pages/privacy'
  get 'pages/terms'
  get 'pages/deleted'

  get 'contact/show'
  post 'contact/submit'
  get 'contact/submitted'

  resources :events, only: [:show] do
    member do
      get :review
      get :reserve
    end

    get :support, to: 'support#index'
    get 'support/:id/new', to: 'support#new', as: :new_support
    post 'support/:id', to: 'support#create', as: :create_support
    delete 'support/:id', to: 'support#destroy', as: :destroy_support

    resources :reservations, only: %i[create destroy] do
      resources :items, except: :show do
        member do
          delete :code, action: :delete_code
        end
      end
      member do
        get :import
        post :import
      end
      get 'import/:id', to: 'reservations#import_from', as: :import_from

      resources :labels, only: %i[index create]
      resource :review
    end

    get 'reservations/create', to: 'reservations#create'

    resource :notification, only: %i[create destroy]
  end

  resource :seller do
    match :resend_activation, via: %i[get post]
    member do
      post :mailing, action: :allow_mailing
      delete :mailing, action: :block_mailing
    end
  end

  get 'sellers/login/:token', to: 'sellers#login', as: :login_seller
  post 'sellers/login/:token', to: 'sellers#reenter', as: :reenter_seller
  get 'sellers/register', to: redirect('/seller/new')

  namespace :admin do
    get '', controller: :pages, action: :home
    resources :events, except: :destroy do
      resources :reviews
      resources :reservations do
        collection do
          get :new_bulk
          post :create_bulk
        end
      end
      resources :suspensions
      resources :rentals
      resources :support_types do
        collection do
          get :print
        end
        resources :supporters
      end
      resources :messages, only: [] do
        collection do
          post :invitation
          post :reservation_closing
          post :reservation_closed
          post :finished
        end
      end
      member do
        get :stats
        get :data
        get :bill
        get :report
        get :labels
      end
    end
    resource :client, only: [:edit, :update]

    resources :sellers do
      resources :emails, only: [:index, :show]
    end
    resources :categories do
      resources :sizes
    end
    resources :stock_items do
      collection do
        get :print, action: :print
      end
    end
    resources :message_templates, only: %i[index edit update destroy]
    resources :reservations do
      resources :items do
        member do
          delete :code, action: :delete_code
        end
        collection do
          delete :codes, action: :delete_all_codes
          get :labels, action: :labels
          post :labels, action: :create_labels
        end
      end
    end
    get 'emails', controller: :emails
    post 'emails', controller: :emails, action: :create

    resources :users

    resource :change_password, only: %i[edit update]
    resource :reset_password, only: %i[new create]
    get 'reset_password/token/:token', to: 'reset_password#edit', as: :reset_password_edit
    patch 'reset_password/token/:token', to: 'reset_password#update', as: :reset_password_update

    get 'login', controller: :sessions, action: :new
    post 'login', controller: :sessions, action: :create
    get 'logout', controller: :sessions, action: :destroy
  end

  namespace :api, defaults: { format: 'json' } do
    resource :event, only: [:show] do
      member do
        post :transactions
      end
    end
  end
  get '*unmatched_route', to: 'application#not_found'
end

app/models/suspension.rb
class Suspension < ApplicationRecord
  belongs_to :event
  belongs_to :seller, -> { with_deleted }, inverse_of: :suspensions

  validates :seller, :event, :reason, presence: true
  validates :seller_id, uniqueness: { scope: :event_id }

  def self.search(needle)
    return all if needle.blank?

    joins(:seller).where.has { sift(:full_text_search, needle) | seller.sift(:full_text_search, needle) }
  end

  sifter :full_text_search do |needle|
    pattern = "%#{needle}%"
    reason.matches pattern
  end
end

app/controllers/admin/suspensions_controller.rb
module Admin
  class SuspensionsController < AdminController
    before_action :set_event
    before_action :set_suspension, only: %i[edit update destroy]

    def index
      @suspensions = query.search(params[:search], @page, column_order)
    end

    def new
      @sellers = query.suspensible_sellers.order :first_name, :last_name
    end

    def create
      reason = params[:suspension][:reason]
      seller_ids = params[:suspension][:seller_id].reject(&:empty?)
      suspensions = query.create(seller_ids, reason)
      redirect_to admin_event_suspensions_path, notice: t('.success', count: suspensions.count)
    end

    def edit; end

    def update
      if @suspension.update(suspension_params)
        redirect_to admin_event_suspensions_path, notice: t('.success')
      else
        render :edit
      end
    end

    def destroy
      @suspension.destroy
      redirect_to admin_event_suspensions_path, notice: t('.success')
    end

    def searchable?
      action_name == 'index'
    end

    private

    def set_event
      @event = current_client.events.find params[:event_id]
    end

    def query
      SuspensionsQuery.new(@event)
    end

    def set_suspension
      @suspension = query.find(params[:id])
    end

    def suspension_params
      params.require(:suspension).permit :reason
    end
  end
end

app/views/admin/suspensions/edit.html.haml
- content_for :title, t('.title')
= simple_form_for [:admin, @event, @suspension] do |f|
  = f.error_notification
  .form-inputs
    = f.input :reason

  .form-actions
    = f.button :submit

app/views/admin/suspensions/index.html.haml
- content_for :title, t('.title')
%table.table.table-condensed.table-hover.table-striped
  %tr
    %th= Seller.human_attribute_name :name
    %th= Seller.human_attribute_name :city
    %th= Seller.human_attribute_name :email
    %th= Suspension.human_attribute_name :reason
    %th= link_to t('.new'), new_admin_event_suspension_path(@event), type: :primary, icon: :file
  - @suspensions.each do |suspension|
    %tr
      %td= link_to suspension.seller.name, admin_seller_path(suspension.seller)
      %td= suspension.seller.city
      %td= suspension.seller.email
      %td= suspension.reason
      %td
        = icon_link_to t('edit'), edit_admin_event_suspension_path(@event, suspension), type: :primary, icon: :pencil
        = destroy_icon_link_to admin_event_suspension_path(suspension.event, suspension)
%p= paginate @suspensions, event_id: @event.id
= render '/confirm', locals: { type: :danger }

app/views/admin/suspensions/new.html.haml
- content_for :title, t('.title')
= simple_form_for [:admin, @event, Suspension.new] do |f|
  = f.error_notification
  .form-inputs
    = f.association :seller, label_method: :label_for_selects, collection: @sellers, input_html: { multiple: true }
    = f.input :reason
  .form-actions
    = f.button :submit