config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  post 'mail', to: 'mail#receive', as: :receive_mail

  get 'pages/home'
  get 'pages/index'
  get 'pages/imprint'
  get 'pages/privacy'
  get 'pages/terms'
  get 'pages/deleted'

  get 'contact/show'
  post 'contact/submit'
  get 'contact/submitted'

  resources :events, only: [:show] do
    member do
      get :review
      get :reserve
    end

    get :support, to: 'support#index'
    get 'support/:id/new', to: 'support#new', as: :new_support
    post 'support/:id', to: 'support#create', as: :create_support
    delete 'support/:id', to: 'support#destroy', as: :destroy_support

    resources :reservations, only: %i[create destroy] do
      resources :items, except: :show do
        member do
          delete :code, action: :delete_code
        end
      end
      member do
        get :import
        post :import
      end
      get 'import/:id', to: 'reservations#import_from', as: :import_from

      resources :labels, only: %i[index create]
      resource :review
    end

    get 'reservations/create', to: 'reservations#create'

    resource :notification, only: %i[create destroy]
  end

  resource :seller do
    match :resend_activation, via: %i[get post]
    member do
      post :mailing, action: :allow_mailing
      delete :mailing, action: :block_mailing
    end
  end

  get 'sellers/login/:token', to: 'sellers#login', as: :login_seller
  post 'sellers/login/:token', to: 'sellers#reenter', as: :reenter_seller
  get 'sellers/register', to: redirect('/seller/new')

  namespace :admin do
    get '', controller: :pages, action: :home
    resources :events, except: :destroy do
      resources :reviews
      resources :reservations do
        collection do
          get :new_bulk
          post :create_bulk
        end
      end
      resources :suspensions
      resources :rentals
      resources :support_types do
        collection do
          get :print
        end
        resources :supporters
      end
      resources :messages, only: [] do
        collection do
          post :invitation
          post :reservation_closing
          post :reservation_closed
          post :finished
        end
      end
      member do
        get :stats
        get :data
        get :bill
        get :report
        get :labels
      end
    end
    resource :client, only: [:edit, :update]

    resources :sellers do
      resources :emails, only: [:index, :show]
    end
    resources :categories do
      resources :sizes
    end
    resources :stock_items do
      collection do
        get :print, action: :print
      end
    end
    resources :message_templates, only: %i[index edit update destroy]
    resources :reservations do
      resources :items do
        member do
          delete :code, action: :delete_code
        end
        collection do
          delete :codes, action: :delete_all_codes
          get :labels, action: :labels
          post :labels, action: :create_labels
        end
      end
    end
    get 'emails', controller: :emails
    post 'emails', controller: :emails, action: :create

    resources :users

    resource :change_password, only: %i[edit update]
    resource :reset_password, only: %i[new create]
    get 'reset_password/token/:token', to: 'reset_password#edit', as: :reset_password_edit
    patch 'reset_password/token/:token', to: 'reset_password#update', as: :reset_password_update

    get 'login', controller: :sessions, action: :new
    post 'login', controller: :sessions, action: :create
    get 'logout', controller: :sessions, action: :destroy
  end

  namespace :api, defaults: { format: 'json' } do
    resource :event, only: [:show] do
      member do
        post :transactions
      end
    end
  end
  get '*unmatched_route', to: 'application#not_found'
end

app/models/event.rb
class Event < ApplicationRecord
  enum kind: { commissioned: 0, direct: 1 }
  belongs_to :client
  has_one :bill, dependent: :destroy
  has_many :reservations, -> { order :id }, inverse_of: :event
  has_many :reviews, through: :reservations
  has_many :items, -> { order 'reservations.number' }, through: :reservations
  has_many :notifications, -> { order :id }, inverse_of: :event
  has_many :messages, dependent: :delete_all
  has_many :support_types, dependent: :delete_all
  has_many :suspensions, dependent: :delete_all
  has_many :rentals, dependent: :delete_all
  has_many :sold_stock_items, dependent: :delete_all
  has_many :stock_items, through: :sold_stock_items
  has_many :handover_periods, -> { where(kind: :handover).order(:min) },
           class_name: 'TimePeriod',
           dependent: :delete_all,
           inverse_of: :event
  has_many :shopping_periods, -> { where(kind: :shopping).order(:min) },
           class_name: 'TimePeriod',
           dependent: :delete_all,
           inverse_of: :event
  has_many :pickup_periods, -> { where(kind: :pickup).order(:min) },
           class_name: 'TimePeriod',
           dependent: :delete_all,
           inverse_of: :event
  has_many :transactions, dependent: :destroy

  accepts_nested_attributes_for :shopping_periods, :handover_periods, :pickup_periods,
                                allow_destroy: true, reject_if: :all_blank

  validates :client, :name, :max_reservations, :reservation_fee, :number, presence: true
  validates :max_items_per_reservation, :price_precision, :commission_rate,
            presence: { if: -> { kind == :commissioned } }
  validates :reservation_fee, numericality: { greater_than_or_equal_to: 0.0, less_than: 50 }
  validates :max_reservations, numericality: { greater_than: 0, only_integer: true }
  validates :reservation_start, :reservation_end, presence: true
  validate :exclusive_reservation_fee_options

  with_options if: :commissioned? do
    validates :price_precision, numericality: { greater_than_or_equal_to: 0.1, less_than_or_equal_to: 1 }
    validates :commission_rate, numericality: { greater_than_or_equal_to: 0.0, less_than: 1 }
    validates :max_items_per_reservation, numericality: { greater_than: 0, only_integer: true }
    validates :max_donations_per_reservation, numericality: { greater_than: 0, only_integer: true, allow_nil: true }
    validates :price_factor, numericality: { greater_than_or_equal_to: 1.0, allow_nil: true }
  end

  validates :number, numericality: { greater_than: 0, only_integer: true }, uniqueness: { scope: :client_id }

  before_validation :create_number

  scope :reservation_started, -> { where.has { reservation_start <= Time.now } }
  scope :reservation_not_yet_ended, -> { where.has { reservation_end >= Time.now } }
  scope :within_reservation_time, -> { reservation_started.reservation_not_yet_ended }
  scope :without_reservation_for, ->(seller) { where.not(id: seller.reservations.map(&:event_id)) }
  scope :current_or_upcoming, -> { joining { shopping_periods }.where.has { shopping_periods.max >= Time.now } }
  scope :with_sent, ->(category) { joining { messages }.where.has { messages.category == category.to_s } }
  scope :reservable, -> { within_reservation_time.with_available_reservations }
  scope :past, -> { joining { shopping_periods }.where.has { shopping_periods.max < 2.days.ago } }
  scope :without_bill, -> { where.not(bill) }

  def self.in_need_of_support
    where(support_system_enabled: true).joining { support_types }.select do |event|
      event.support_types.any? { |support_type| support_type.capacity > support_type.supporters.count }
    end
  end

  def donations_limited?
    donation_of_unsold_items_enabled && max_donations_per_reservation.present?
  end

  def self.with_available_reservations
    joining { reservations.outer }.grouping { id }.when_having { reservations.id.count < max_reservations }
  end

  def reservable_by?(seller)
    reservations_left? && can_add_to_notifications?(seller)
  end

  def notifiable_by?(seller)
    seller.client.reservation_by_seller_allowed? && can_add_to_notifications?(seller)
  end

  def reviewed_by?(seller)
    reservations.any? { |reservation| reservation.seller == seller && reservation.review.present? }
  end

  def reservations_left
    [max_reservations - reservations.count, 0].max
  end

  def reservations_left?
    reservations_left.positive?
  end

  def max_reservations_per_seller
    self[:max_reservations_per_seller] || 1
  end

  def reservation_fee=(number)
    number.tr!(',', '.') if number.is_a? String
    self[:reservation_fee] = number.try(:to_d)
  end

  def to_s
    name || super
  end

  def past?
    shopping_periods&.last&.max&.past?
  end

  def item_count
    reservations.joins(:items).count
  end

  def checked_in_item_count
    reservations.joins(:items).merge(Item.checked_in).count
  end

  def checked_out_item_count
    reservations.joins(:items).merge(Item.checked_out).count
  end

  def items_with_label_count
    reservations.joins(:items).merge(Item.with_label).count
  end

  def sold_item_count
    reservations.joins(:items).merge(Item.sold).count
  end

  def sold_item_sum
    sum = reservations.joins(:items).merge(Item.sold).sum(:price) +
          sold_stock_items.joins(:stock_item).sum('price * amount')
    sum *= price_factor if price_factor.present?
    sum
  end

  def reservation_fees_sum
    reservations.all.map(&:fee).sum
  end

  def revenue
    reservation_fees_sum + sold_item_sum
  end

  def rental_fees
    rentals.all.map { |r| r.amount * r.hardware.price }.sum
  end

  def system_fees
    number == 1 ? 0 : revenue / 100
  end

  def total_fees
    rental_fees + system_fees
  end

  def sold_stock_item_count
    sold_stock_items.map(&:amount).inject(:+)
  end

  def sold_item_percentage
    return 0 if item_count.zero?

    sold_item_count * 100 / item_count
  end

  def top_sellers
    result = reservations.unscope(:order).joins(:items).merge(Item.sold).grouping { number }.selecting do
      [number, items.id.count.as('count')]
    end
    result.ordering { items.id.count.desc }.map { |e| [e.number, e.count] }
  end

  def items_per_category
    reservations.joining { items.category }.grouping { items.category.name }
                .selecting { [items.category.name, items.id.count.as('count')] }
                .ordering { items.id.count.desc }.map { |e| [e.name, e.count] }
  end

  def sold_items_per_category
    reservations.joining { items.category }.merge(Item.sold).grouping { items.category.name }
                .selecting { [items.category.name, items.id.count.as('count')] }
                .ordering { items.id.count.desc }.map { |e| [e.name, e.count] }
  end

  def sellers_per_zip_code
    reservations.joining { seller }.grouping { seller.zip_code }.selecting do
      [seller.zip_code, seller.id.count.as('count')]
    end
  end

  def sellers_per_city
    sellers_per_zip_code.map { |e| [Rails.application.config.zip_codes[e.zip_code] || e.zip_code, e.count] }
                        .each_with_object({}) { |(z, c), h| h[z] = (h[z] || 0) + c }
                        .to_a.sort { |a, b| b.second <=> a.second }
  end

  before_save do
    self.token ||= loop do
      random_token = SecureRandom.urlsafe_base64(8, false)
      break random_token unless self.class.exists?(token: random_token)
    end
  end

  private

  def can_add_to_notifications?(seller)
    !max_reservations_reached_for?(seller) &&
      !suspensions.find_by(seller: seller) &&
      !notifications.find_by(seller: seller)
  end

  def max_reservations_reached_for?(seller)
    reservations.where(seller: seller).count >= max_reservations_per_seller
  end

  def create_number
    return if client.nil? || number.present?

    current_max = client.events.maximum(:number) || 0
    self.number = current_max + 1
  end

  def exclusive_reservation_fee_options
    return unless reservation_fee_based_on_item_count? && reservation_fees_payed_in_advance?

    errors.add :reservation_fees_payed_in_advance, :fee_based_on_item_count
  end
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < AdminController
    before_action :init_event, only: %i[edit update show stats data bill report labels]

    def init_event
      @event = current_client.events.find params[:id]
    end

    def index
      @events = current_client.events.page(@page).joining { shopping_periods.outer }.order(column_order).distinct
    end

    def new
      date = 1.month.from_now.at_midday
      @event = current_client.events.build price_precision: current_client.price_precision,
                                           precise_bill_amounts: current_client.precise_bill_amounts,
                                           commission_rate: current_client.commission_rate,
                                           reservation_fee: current_client.reservation_fee,
                                           kind: :commissioned,
                                           donation_of_unsold_items_enabled: current_client.donation_of_unsold_items,
                                           gates: current_client.gates,
                                           reservation_start: date - 2.weeks, reservation_end: date - 2.days,
                                           shopping_periods_attributes: create_period(date),
                                           handover_periods_attributes: create_period(date - 1.day),
                                           pickup_periods_attributes: create_period(date + 1.day)
    end

    def create
      @event = current_client.events.create(event_params)
      if @event.valid?
        AdminMailer.event_created(@event).deliver_later
        redirect_to admin_events_path, notice: t('.success')
      else
        render :new
      end
    end

    def edit; end

    def update
      if @event.update event_params
        auto_reserve(@event)
        redirect_to admin_events_path, notice: t('.success')
      else
        render :edit
      end
    end

    def show; end

    def stats; end

    def data
      send_data CreateEventData.new(current_client).call(@event), filename: 'flohmarkthelfer.data'
    end

    def bill
      send_data @event.bill.document, filename: "rechnung_flohmarkthelfer_#{@event.bill.number}.pdf",
                                      type: 'application/pdf'
    end

    def report
      send_data CreateEventReport.new(@event).call, filename: 'artikelliste.txt', type: 'text/plain'
    end

    def labels
      CreateLabelsDocumentJob.perform_later @event
      redirect_to admin_event_path(@event), notice: t('.success', mail_address: current_client.mail_address)
    end

    private

    def create_period(date)
      [min: date, max: date + 2.hours]
    end

    def event_params
      params.require(:event).permit :name, :details, :max_reservations, :kind, :confirmed,
                                    :max_items_per_reservation, :max_reservations_per_seller,
                                    :max_donations_per_reservation,
                                    :price_precision, :precise_bill_amounts,
                                    :commission_rate, :reservation_fee,
                                    :reservation_fee_based_on_item_count,
                                    :reservation_fees_payed_in_advance,
                                    :donation_of_unsold_items_enabled,
                                    :support_system_enabled, :supporters_can_retire,
                                    :reservation_start, :reservation_end,
                                    :handover_start, :handover_end,
                                    :pickup_start, :pickup_end,
                                    :gates, :price_factor,
                                    shopping_periods_attributes: %i[id min max _destroy],
                                    handover_periods_attributes: %i[id min max _destroy],
                                    pickup_periods_attributes: %i[id min max _destroy]
    end
  end
end

app/controllers/api/events_controller.rb
module Api
  class EventsController < ApplicationController
    skip_before_action :verify_authenticity_token

    before_action :init_event

    def show
      send_data CreateEventData.new(@event.client).call(@event), filename: 'flohmarkthelfer.data'
    end

    def transactions
      ImportTransactions.new(@event).call(transaction_params)
      head :no_content
    end

    private

    def init_event
      authenticate_or_request_with_http_token do |token, _options|
        Rails.logger.info "Token: #{token}"
        @event = Event.find_by token: token
        @event.present?
      end
    end

    def transaction_params
      params.permit(_json: [:id, :type, :date, { items: [] }]).to_h.first.last
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :init_event
  before_action :only_with_reservation, :only_after_event_passed, except: :reserve

  def show; end

  def review
    reservation = current_seller.reservations.find_by event: @event
    redirect_to new_event_reservation_review_path(@event, reservation)
  end

  def reserve
    redirect_to event_reservations_create_path(@event)
  end

  private

  def init_event
    @event = current_client.events.find params[:id]
  end
end

app/helpers/events_helper.rb
module EventsHelper
  include TimePeriodsHelper

  def shopping_time(event)
    period event.shopping_periods, exact: event.confirmed?
  end

  def handover_time(event)
    period event.handover_periods, exact: true
  end

  def pickup_time(event)
    period event.pickup_periods, exact: true
  end

  def waiting_list_position(event, seller)
    event.notifications.pluck(:seller_id).index(seller.id) + 1
  end
end

app/views/admin/events/_form.html.haml
= simple_form_for [:admin, @event] do |f|
  = f.error_notification
  .form-inputs
    = f.input :name
    = f.input :details, hint: markdown(t('hints.markdown')), input_html: { class: 'markdown_editor', rows: 10 }
    = f.input :max_reservations
    = f.input :kind, collection: { t(:commissioned) => :commissioned, t(:direct) => :direct }, as: :radio_buttons
    = f.input :max_items_per_reservation
    = f.input :max_reservations_per_seller
    = f.input :confirmed
    = f.input :reservation_start, as: :date_time_picker, input_html: { value: l(f.object.reservation_start, format: :short) }
    = f.input :reservation_end, as: :date_time_picker, input_html: { value: l(f.object.reservation_end, format: :short) }
    = render 'periods', attribute: :handover_periods, f: f
    = render 'periods', attribute: :shopping_periods, f: f
    = render 'periods', attribute: :pickup_periods, f: f
    = f.input :price_precision, hint: t('.price_precision.hint')
    = f.input :precise_bill_amounts
    = f.input :commission_rate, hint: t('.commission_rate.hint')
    = f.input :reservation_fee
    = f.input :reservation_fee_based_on_item_count
    = f.input :reservation_fees_payed_in_advance
    = f.input :donation_of_unsold_items_enabled
    = f.input :max_donations_per_reservation
    = f.input :support_system_enabled
    = f.input :supporters_can_retire
    = f.input :gates

  .form-actions
    = f.button :submit

app/views/admin/events/_periods.html.haml
%div{id: attribute}
  %strong= Event.human_attribute_name attribute
  = f.simple_fields_for attribute do |s|
    = render 'time_period_fields', f: s
  .links
    = link_to_add_association 'Weiteres Zeitfenster hinzufügen', f, attribute, partial: 'time_period_fields'

app/views/admin/events/_shopping_period_fields.html.haml
.nested-fields
  = f.input :min, as: :date_time_picker, input_html: { value: f.object.min ? l(f.object.min, format: :short) : '' }
  = f.input :max, as: :date_time_picker, input_html: { value: f.object.max ? l(f.object.max, format: :short) : '' }
  = link_to_remove_association f, class: 'btn btn-warning' do
    = enhance_name_with_icon '', icon: :minus

app/views/admin/events/_time_period_fields.html.haml
.nested-fields
  = f.input :min, as: :date_time_picker, input_html: { value: f.object.min ? l(f.object.min, format: :short) : '' }
  = f.input :max, as: :date_time_picker, input_html: { value: f.object.max ? l(f.object.max, format: :short) : '' }
  = link_to_remove_association f, class: 'btn btn-warning' do
    = enhance_name_with_icon '', icon: :minus

app/views/admin/events/index.html.haml
- content_for :title, t('.title')
%table.table.table-condensed.table-hover.table-striped
  %tr
    %th= t('position')
    %th= sort_link_to Event, :name
    %th= sort_link_to TimePeriod, :min, Event.human_attribute_name(:shopping_periods)
    %th= sort_link_to Event, :reservation_start
    %th= link_to t('.new'), new_admin_event_path, type: :primary, icon: :file

  - @events.each_with_index do |event, index|
    %tr
      %td= @events.offset + index + 1
      %td= event.name
      %td= shopping_time event
      %td= l(event.reservation_start)
      %td.btn-group
        = icon_link_to t('show'), [:admin, event], type: :primary, icon: :eye_open
        = icon_link_to t('edit'), edit_admin_event_path(event), type: :success, icon: :pencil
%p= paginate @events

app/views/admin/events/show.html.haml
- content_for :title, t('.title')
%dl
  %dt= Event.human_attribute_name :name
  %dd= @event.name
  %dt= Event.human_attribute_name :details
  %dd= markdown @event.details
  - %i[max_reservations max_items_per_reservation max_reservations_per_seller reservation_start reservation_end].each do |attribute|
    %dt= Event.human_attribute_name attribute
    %dd= ([Date, DateTime, Time, ActiveSupport::TimeWithZone].include? @event[attribute].class) ? l(@event[attribute]) : @event[attribute]
  %dt= Event.human_attribute_name :token
  %dd
    %strong
      %code= @event.token
  %dt= Event.human_attribute_name :kind
  %dd= t(@event.kind)
  %dt= Event.human_attribute_name :handover_periods
  %dd= handover_time @event
  %dt= Event.human_attribute_name :shopping_periods
  %dd= shopping_time @event
  %dt= Event.human_attribute_name :pickup_periods
  %dd= pickup_time @event
  - if @event.commission_rate.present?
    %dt= Event.human_attribute_name :commission_rate
    %dd= number_to_percentage @event.commission_rate*100, precision: 0
  - if @event.reservation_fee.present?
    %dt
      = Event.human_attribute_name :reservation_fee
      - if @event.reservation_fee_based_on_item_count?
        pro Artikel
    %dd= number_to_currency @event.reservation_fee
  - if @event.price_factor.present?
    %dt= Event.human_attribute_name :price_factor
    %dd= number_to_percentage @event.price_factor*100, precision: 0
  %dt= Event.human_attribute_name :donation_of_unsold_items_enabled
  %dd= t(@event.donation_of_unsold_items_enabled?.to_s)
  %dt= Event.human_attribute_name :max_donations_per_reservation
  %dd= @event.max_donations_per_reservation
  %dt= Event.human_attribute_name :support_system_enabled
  %dd= t(@event.support_system_enabled?.to_s)
  %dt= Event.human_attribute_name :supporters_can_retire
  %dd= t(@event.supporters_can_retire?.to_s)
  %dt= Event.human_attribute_name :gates
  %dd= t(@event.gates?.to_s)

.btn-group
  = link_to 'Bearbeiten', edit_admin_event_path(@event), type: :primary, icon: :pencil
  = link_to 'Reservierungen', admin_event_reservations_path(@event), type: :primary, icon: :check
  = link_to 'Sperren', admin_event_suspensions_path(@event), type: :primary, icon: :lock
  = link_to 'Leihgeräte', admin_event_rentals_path(@event), type: :primary, icon: :shopping_cart
  = link_to 'Statistiken', stats_admin_event_path(@event), type: :primary, icon: :signal
  = link_to 'Helferverwaltung', admin_event_support_types_path(@event), type: :primary, icon: :leaf
  - if @event.items_with_label_count < @event.item_count
    = confirm_link_to data_admin_event_path(@event, format: :json), name: 'Daten herunterladen', method: :get, message: t('.confirm.download', item_count: @event.item_count, label_count: @event.items_with_label_count), type: :primary, icon: :download
  - else
    = link_to 'Daten herunterladen', data_admin_event_path(@event, format: :json), type: :primary, icon: :download
  - if @event.reservation_end.past? && @event.items_with_label_count == @event.item_count
    = link_to 'Etiketten drucken', labels_admin_event_path(@event), type: :primary, icon: :print
  - if @event.past?
    = link_to 'Bewertungen', admin_event_reviews_path(@event), type: :primary, icon: :heart
  - if @event.bill.present?
    = link_to 'Rechnung', bill_admin_event_path(@event), type: :primary, icon: :euro
%p
.btn-group
  - if !Message.exists?(event: @event, category: :invitation) && @event.reservation_end.future?
    = link_to 'Reservierungseinladung verschicken', invitation_admin_event_messages_path(@event), method: :post, type: :primary, icon: :envelope
  - if !Message.exists?(event: @event, category: :reservation_closing) && @event.reservation_start.past? && @event.reservation_end.future?
    = link_to 'Erinnerungsmail vor Bearbeitungsschluss verschicken', reservation_closing_admin_event_messages_path(@event), method: :post, type: :primary, icon: :envelope
  - if !Message.exists?(event: @event, category: :reservation_closed) && @event.reservation_end.past?
    = link_to 'Bearbeitungsabschlussmail verschicken', reservation_closed_admin_event_messages_path(@event), method: :post, type: :primary, icon: :envelope
  - if !Message.exists?(event: @event, category: :finished) && @event.past?
    = confirm_link_to finished_admin_event_messages_path(@event), name: 'Abschlussmail verschicken', method: :post, type: :primary, icon: :envelope, message: t('.confirm.send_finished', transaction_count: @event.transactions.count, sold_item_count: @event.sold_item_count)
%p
- %i[invitation reservation_closing reservation_closed finished].each do |category|
  - if message = @event.messages.find_by(category: category)
    = t(".message_sent.#{category}", sent_count: message.sent_count, scheduled_count: message.scheduled_count)
    %br

= render '/confirm', locals: {}

app/views/admin/events/stats.html.haml
- content_for :title, t('.title')
%h3 Artikel
%p= link_to 'Artikelliste herunterladen', report_admin_event_path(@event), type: :primary, icon: :list_alt
%ul
  %li
    gesamt: #{@event.item_count}
    = pie_chart @event.items_per_category
    %a(data-toggle='collapse' href='#items_per_category_table_collapser' aria-expanded=false aria-controls='items_per_category_table_collapser') Tabelle anzeigen
    .collapse#items_per_category_table_collapser
      %table.table.table-condensed.table-hover.table-striped#items_per_category_table
        %thead
          %tr
            %th Kategorie
            %th Artikelanzahl
        %tbody
          - @event.items_per_category.each do |category, item_count|
            %tr
              %td= category
              %td= item_count
  %li Etiketten: #{@event.items_with_label_count}
  %li
    verkauft: #{@event.sold_item_count} (#{number_to_percentage(@event.sold_item_percentage, precision: 0)})
    = pie_chart @event.sold_items_per_category
    %a(data-toggle='collapse' href='#sold_items_per_category_table_collapser' aria-expanded=false aria-controls='sold_items_per_category_table_collapser') Tabelle anzeigen
    .collapse#sold_items_per_category_table_collapser
      %table.table.table-condensed.table-hover.table-striped#sold_items_per_category_table
        %thead
          %tr
            %th Kategorie
            %th Artikelanzahl
        %tbody
          - @event.sold_items_per_category.each do |category, item_count|
            %tr
              %td= category
              %td= item_count
  %li
    verkaufte Stammartikel: #{@event.sold_stock_item_count}
    %a(data-toggle='collapse' href='#sold_stock_items_table_collapser' aria-expanded=false aria-controls='sold_stock_items_table_collapser') Tabelle anzeigen
    .collapse#sold_stock_items_table_collapser
      %table.table.table-condensed.table-hover.table-striped#sold_stock_items_table
        %thead
          %tr
            %th Artikel
            %th Anzahl
        %tbody
          - @event.sold_stock_items.each do |sold_stock_item|
            %tr
              %td= sold_stock_item.stock_item.description
              %td= sold_stock_item.amount
  %li Artikelumsatz: #{number_to_currency(@event.sold_item_sum)}
  %li Reservierungsgebühren: #{number_to_currency(@event.reservation_fees_sum)}
  %li Gesamtumsatz: #{number_to_currency(@event.revenue)}
  %li Leihgebühren: #{number_to_currency(@event.rental_fees)}
  %li Systemgebühren: #{number_to_currency(@event.system_fees)}
  %li Gesamtgebühren: #{number_to_currency(@event.total_fees)}
  - if @event.gates
    %li eingecheckt: #{@event.checked_in_item_count}
    %li ausgecheckt: #{@event.checked_out_item_count}
%h3 Verkäufer
%ul
  %li
    Reservierungen: #{@event.reservations.count} / #{@event.max_reservations}
    = pie_chart @event.sellers_per_city
    %a(data-toggle='collapse' href='#sellers_per_city_table_collapser' aria-expanded=false aria-controls='selles_per_city_table_collapser') Tabelle anzeigen
    .collapse#sellers_per_city_table_collapser
      %table.table.table-condensed.table-hover.table-striped#sellers_per_city_table
        %thead
          %tr
            %th Ort
            %th Verkäuferzahl
        %tbody
          - @event.sellers_per_city.each do |city, seller_count|
            %tr
              %td= city
              %td= seller_count
  %li
    Warteliste: #{@event.notifications.count}
    %a(data-toggle='collapse' href='#notifications_collapser' aria-expanded=false aria-controls='notifications_collapser') anzeigen
    .collapse#notifications_collapser
      %table.table.table-condensed.table-hover.table-striped
        %thead
          %tr
            %th Position
            %th Name
            %th Stadt
        %tbody
          - @event.notifications.each_with_index do |notification, index|
            %tr
              %td= index + 1
              %td= notification.seller.name
              %td= notification.seller.city