config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  post 'mail', to: 'mail#receive', as: :receive_mail

  get 'pages/home'
  get 'pages/index'
  get 'pages/imprint'
  get 'pages/privacy'
  get 'pages/terms'
  get 'pages/deleted'

  get 'contact/show'
  post 'contact/submit'
  get 'contact/submitted'

  resources :events, only: [:show] do
    member do
      get :review
      get :reserve
    end

    get :support, to: 'support#index'
    get 'support/:id/new', to: 'support#new', as: :new_support
    post 'support/:id', to: 'support#create', as: :create_support
    delete 'support/:id', to: 'support#destroy', as: :destroy_support

    resources :reservations, only: %i[create destroy] do
      resources :items, except: :show do
        member do
          delete :code, action: :delete_code
        end
      end
      member do
        get :import
        post :import
      end
      get 'import/:id', to: 'reservations#import_from', as: :import_from

      resources :labels, only: %i[index create]
      resource :review
    end

    get 'reservations/create', to: 'reservations#create'

    resource :notification, only: %i[create destroy]
  end

  resource :seller do
    match :resend_activation, via: %i[get post]
    member do
      post :mailing, action: :allow_mailing
      delete :mailing, action: :block_mailing
    end
  end

  get 'sellers/login/:token', to: 'sellers#login', as: :login_seller
  post 'sellers/login/:token', to: 'sellers#reenter', as: :reenter_seller
  get 'sellers/register', to: redirect('/seller/new')

  namespace :admin do
    get '', controller: :pages, action: :home
    resources :events, except: :destroy do
      resources :reviews
      resources :reservations do
        collection do
          get :new_bulk
          post :create_bulk
        end
      end
      resources :suspensions
      resources :rentals
      resources :support_types do
        collection do
          get :print
        end
        resources :supporters
      end
      resources :messages, only: [] do
        collection do
          post :invitation
          post :reservation_closing
          post :reservation_closed
          post :finished
        end
      end
      member do
        get :stats
        get :data
        get :bill
        get :report
        get :labels
      end
    end
    resource :client, only: [:edit, :update]

    resources :sellers do
      resources :emails, only: [:index, :show]
    end
    resources :categories do
      resources :sizes
    end
    resources :stock_items do
      collection do
        get :print, action: :print
      end
    end
    resources :message_templates, only: %i[index edit update destroy]
    resources :reservations do
      resources :items do
        member do
          delete :code, action: :delete_code
        end
        collection do
          delete :codes, action: :delete_all_codes
          get :labels, action: :labels
          post :labels, action: :create_labels
        end
      end
    end
    get 'emails', controller: :emails
    post 'emails', controller: :emails, action: :create

    resources :users

    resource :change_password, only: %i[edit update]
    resource :reset_password, only: %i[new create]
    get 'reset_password/token/:token', to: 'reset_password#edit', as: :reset_password_edit
    patch 'reset_password/token/:token', to: 'reset_password#update', as: :reset_password_update

    get 'login', controller: :sessions, action: :new
    post 'login', controller: :sessions, action: :create
    get 'logout', controller: :sessions, action: :destroy
  end

  namespace :api, defaults: { format: 'json' } do
    resource :event, only: [:show] do
      member do
        post :transactions
      end
    end
  end
  get '*unmatched_route', to: 'application#not_found'
end

app/models/seller.rb
class Seller < ApplicationRecord
  acts_as_paranoid

  attr_accessor :accept_terms

  belongs_to :client

  # !! we must not specify dependent option as it would delete reservations/supports associations on soft delete
  # we should move away from 'paranoid' to 'paper_trail' or 'discard' to fix this
  has_many :reservations
  has_many :notifications, dependent: :delete_all
  has_many :suspensions, dependent: :delete_all
  has_many :emails, dependent: :delete_all
  has_many :supporters

  validates :client, :email, presence: true
  validates :first_name, :last_name, :street, :zip_code, :city, :phone, presence: { on: :update }
  validates :first_name, :last_name, :street, :zip_code, :city, :phone, presence: { on: :create }
  validates :accept_terms, acceptance: { on: :create }
  validates :default_reservation_number, uniqueness: { scope: :client_id, allow_nil: true }
  validates :default_reservation_number, numericality: { greater_than: 0, less_than: 1000, allow_nil: true }

  validates :email, uniqueness: { case_sensitive: false, scope: :client_id, on: :create }
  validates :email, uniqueness: { case_sensitive: false, scope: :client_id, on: :update }
  validates_email_format_of :email
  validates :zip_code, format: { with: /\A\d{5}\z/, on: :update }
  validates :zip_code, format: { with: /\A\d{5}\z/, on: :create }
  validates :phone, format: { with: %r(\A\(?(\+ ?49|0)[ \(\)/\-\d]{5,30}[0-9]\z), on: :update }
  validates :phone, format: { with: %r(\A\(?(\+ ?49|0)[ \(\)/\-\d]{5,30}[0-9]\z), on: :create }

  validate :email_exists, on: :resend_activation
  validate :default_reservation_number_in_range

  scope :with_mailing, -> { where.has { mailing.eq true } }
  scope :active, -> { where.has { active.eq true } }
  scope :without_reservation_for, ->(event) { where.not(id: event.reservations.map(&:seller_id)) }
  scope :search, ->(needle) { needle.nil? ? all : where.has { sift :full_text_search, needle } }
  scope :available_for_support_type, ->(support_type) { where.not(id: support_type.supporters.map(&:seller_id)) }

  include Statistics

  before_validation do
    email&.downcase!
  end

  before_create do
    self.token ||= loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless self.class.exists?(token: random_token)
    end
  end

  def to_s
    "#{first_name} #{last_name}"
  end

  alias name to_s

  def label_for_selects
    "#{name}, #{city} (#{email})"
  end

  sifter :full_text_search do |needle|
    pattern = "%#{needle}%"
    first_name.matches(pattern) |
      last_name.matches(pattern) |
      street.matches(pattern) |
      zip_code.matches(pattern) |
      city.matches(pattern) |
      email.matches(pattern) |
      phone.matches(pattern)
  end

  def suspended_for?(event)
    suspensions.find_by(event: event).present?
  end

  def self.destroy_everything!(client)
    Seller.unscoped { Email.joins(:seller).where(sellers: { client_id: client.id }).destroy_all }
    Item.joins(reservation: :seller).where(sellers: { client_id: client.id }).destroy_all
    Review.joins(reservation: :seller).where(sellers: { client_id: client.id }).destroy_all
    Reservation.joins(:seller).where(sellers: { client_id: client.id }).destroy_all
    Notification.joins(:seller).where(sellers: { client_id: client.id }).destroy_all
    Suspension.joins(:seller).where(sellers: { client_id: client.id }).destroy_all
    Supporter.joins(:seller).where(sellers: { client_id: client.id }).destroy_all
    Seller.unscoped.where(client_id: client.id).delete_all
  end

  private

  def paranoia_destroy_attributes
    {
      deleted_at: current_time_from_proper_timezone,
      active: nil, mailing: nil,
      first_name: nil, last_name: nil,
      phone: nil, email: nil,
      street: nil,
      city: nil,
      token: nil
    }
  end

  def email_exists
    return if Seller.exists? email: email, client: client

    errors.add :email, :unknown
  end

  def default_reservation_number_in_range
    return if default_reservation_number.nil? || client.nil?

    auto_start = client.auto_reservation_numbers_start || 1
    return if default_reservation_number < auto_start

    errors.add :default_reservation_number, :out_of_range
  end
end

app/controllers/admin/sellers_controller.rb
module Admin
  class SellersController < AdminController
    def index
      @sellers = current_client.sellers.search(params[:search]).page(@page).order(column_order)
    end

    def new
      @seller = current_client.sellers.build
      init_available_numbers
    end

    def create
      @seller = current_client.sellers.build seller_params
      if @seller.save
        redirect_to admin_sellers_path, notice: t('.success')
      else
        render :new
      end
    end

    def edit
      @seller = current_client.sellers.find params[:id]
      init_available_numbers
    end

    def update
      @seller = current_client.sellers.find params[:id]
      if @seller.update seller_params
        redirect_to admin_sellers_path, notice: t('.success')
      else
        render :edit
      end
    end

    def show
      @seller = current_client.sellers.find params[:id]
    end

    def destroy
      if current_client.sellers.find(params[:id]).destroy
        redirect_to admin_sellers_path, notice: t('.success')
      else
        redirect_to admin_sellers_path, alert: t('.failure')
      end
    end

    def searchable?
      action_name == 'index'
    end

    private

    def init_available_numbers
      return if current_client.auto_reservation_numbers_start.blank?

      reserved_numbers = current_client.sellers.where.not(id: @seller.id).pluck(:default_reservation_number)
      @available_numbers = [*1..current_client.auto_reservation_numbers_start - 1] - reserved_numbers
    end

    def seller_params
      params.require(:seller).permit :first_name, :last_name, :street,
                                     :zip_code, :city, :email, :phone,
                                     :default_reservation_number
    end

    def column_order
      result = super
      result = { first_name: @dir, last_name: @dir } if result.keys.first == 'name'
      result
    end
  end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  def show
    @seller = current_seller
    @events = current_client.events.merge(Event.within_reservation_time)
    @events_with_support = current_client.events.merge(Event.in_need_of_support)
  end

  def new
    @seller = current_client.sellers.build
  end

  def edit
    @seller = current_seller
  end

  def create
    @seller = current_client.sellers.build seller_params
    @seller.active = false
    @seller.mailing = true

    if @seller.save
      send_registration_mail @seller
      render :create, status: :ok
    else
      render :new
    end
  end

  def update
    @seller = current_seller
    if @seller.update(seller_params)
      redirect_to seller_path, notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    current_seller.destroy
    reset_session
    redirect_to pages_deleted_path
  end

  def resend_activation
    if request.post?
      @seller = current_client.sellers.build resend_activation_params
      resend_activation_for @seller
    else
      @seller = current_client.sellers.build
    end
  end

  def login
    init_session_and_seller
    goto = params[:goto]
    event = params[:event]
    if %w[show review reserve].include?(goto) && event.present?
      path_method = goto == 'show' ? 'event_path' : "#{goto}_event_path"
      return redirect_to send(path_method, event)
    end
    return block_mailing if goto == 'unsubscribe'

    redirect_to seller_path
  end

  def init_session_and_seller
    reset_session
    sellers = current_client.sellers
    raise UnauthorizedError if sellers.nil?

    seller = sellers.find_by token: params[:token]
    raise UnauthorizedError if seller.blank?

    activate_seller(seller)
    session[:seller_id] = seller.id
  end

  def block_mailing
    current_seller.update!(mailing: false)
    redirect_to seller_path, notice: t('sellers.block_mailing.success')
  end

  def allow_mailing
    current_seller.update!(mailing: true)
    redirect_to seller_path, notice: t('.success')
  end

  private

  def seller_params
    params.require(:seller).permit :first_name, :last_name, :street, :zip_code, :city, :email, :phone, :accept_terms
  end

  def activate_seller(seller)
    return if seller.active

    seller.update active: true
    current_client.events.merge(
      Event.reservation_not_yet_ended.without_reservation_for(seller).with_sent(:invitation)
    ).each do |event|
      SellerMailer.invitation(seller, event).deliver_later if event.reservable_by?(seller)
    end
  end

  def resend_activation_for(seller)
    return unless seller.valid? :resend_activation

    seller = current_client.sellers.find_by email: seller.email
    send_registration_mail(seller)
    render :activation_resent
  end

  def send_registration_mail(seller)
    SellerMailer.registration(seller).deliver_later
  end

  def resend_activation_params
    params.require(:seller).permit :email
  end
end

app/views/sellers/_form.html.haml
= simple_form_for(@seller, url: seller_path) do |f|
  = f.error_notification

  .form-inputs
    = f.input :first_name
    = f.input :last_name
    = f.input :street
    = f.input :zip_code
    = f.input :city
    = f.input :email
    = f.input :phone
    = f.input :accept_terms, as: :boolean, label: t('.accept_terms',
      terms: link_to(t('terms.title'), '#', 'data-toggle' => 'modal', 'data-target' => '#terms'),
      privacy: link_to(t('privacy.title'), '#', 'data-toggle' => 'modal', 'data-target' => '#privacy')).html_safe unless @seller.id
  .form-actions
    = f.button :submit

app/views/sellers/activation_resent.html.haml
- content_for :title, t('.title')
%p Es wurde nochmals die Registrierungsbestätigung an Sie zugesendet. In dieser Mail finden Sie den Link zu Ihrem geschützten Bereich.
%p Falls Sie dies noch nicht getan haben, klicken Sie bitte auf diesen Link, um Ihre Registrierung zu bestätigen. Diese Aktion schaltet Ihre Mail zum Erhalt wichtiger Benachrichtigungen frei.

app/views/sellers/create.html.haml
- content_for :title, t('.title')

:markdown
  Vielen Dank für Ihre Registrierung. Es wird Ihnen innerhalb weniger Minuten eine **eMail zugeschickt**,
  mit der wir die Angabe Ihrer eMail-Adresse verifizieren. Schauen Sie bitte in Ihren Mail-Client
  (z.B. Outlook oder Thunderbird), um den Erhalt dieser Mail zu kontrollieren. Prüfen Sie gegebenenfalls
  auch Ihren SPAM-Ordner.

  In dieser Mail befindet sich ein Link, den Sie **bitte anklicken**, um den Erhalt der Mail zu bestätigen.
  Erst mit Bestätigen wird Ihre **Registrierung aktiv** und Sie werden dann über Neuigkeiten per Mail informiert.

  Hier zur Bestätigung die von Ihnen gemachten Angaben:

= render 'shared/details', instance: @seller,
  attributes: [:first_name, :last_name, :street, :zip_code, :city, :email, :phone]

app/views/sellers/edit.html.haml
- content_for :title, t('.title')
= render 'form'
= link_to 'Zurück ohne Speichern der Änderungen', seller_path, type: :default
%h3 eMail Benachrichtigungen
%p
  Aktuell informieren wir Sie über anstehende Termine und stattfindende Flohmärkte.
  Möchten Sie keine Benachrichtigungen mehr von uns erhalten, benutzen Sie den folgenden Link.
  Sie können sich weiterhin anmelden und sich selbst über Neuigkeiten informieren.
  Die Benachrichtigung können Sie jederzeit wieder aktivieren.
- if @seller.mailing
  %p= link_to 'Ich möchte keine eMails mehr erhalten', mailing_seller_path, method: :delete, icon: :remove, type: :warning
- else
  %p= link_to 'Ich möchte in Zukunft eMail-Benachrichtigungen erhalten', mailing_seller_path, method: :post, icon: :envelope, type: :success
%h3 Daten löschen
%p
  Mit dem folgenden Link können Sie alle Ihre Daten inklusive aller Artikel und Reservierungen löschen.
  Sie können sich jederzeit wieder neu registrieren. Ihre bisher eingebenen Daten sind aber unwiderruflich verloren.
%p= destroy_link_to seller_path, name: t('.destroy.text'), icon: :ban_circle, message: t('.destroy.confirm')
= render '/confirm', locals: { type: :danger }

app/views/sellers/new.html.haml
- content_for :title, t('.title')

.alert.alert-warning= markdown(t('outlook')).html_safe

:markdown
  Sie können sich hier als Interessent für den Verkauf von Ware auf kommenden Kommissionsflohmärkten
  registrieren. Die erfassten Daten dienen in erster Linie dazu,
  um Sie hinsichtlich des weiteren Ablaufs des kommenden Flohmarkts zu kontaktieren und informieren.
  In der Regel findet dies per eMail statt. Auch die Zugangsinformationen zum geschützten Bereich erhalten
  Sie per Mail. Die Telefonnummer wird benötigt, damit wir Sie in dringenden Fällen (bspw. Ware
  verlorengegangen, anderweitig nicht erreichbar) anrufen können. Die Adressdaten dienen der Abrechnung.
  Ebenso werden wir zum Schutz Ihrer Daten Ihre Angaben erfragen, sollten Sie mit uns telefonisch Kontakt
  aufnehmen.

  Pflichtfelder sind <span class="required"><abbr title="Pflichtfeld">entsprechend</abbr></span> gekennzeichnet.

= render 'form'

#terms.modal.fade(tabindex="-1" role="dialog" aria-labelledby="terms-label" aria-hidden="true")
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        %button.close(data-dismiss="modal")
          %span(aria-hidden="true")
            &times;
          %span.sr-only Close
        %h2.modal-title#terms-label= t('terms.title')
      .modal-body
        = markdown(current_client.terms).html_safe
      .modal-footer
        %button.btn.btn-primary(data-dismiss="modal") Schließen
#privacy.modal.fade(tabindex="-1" role="dialog" aria-labelledby="privacy-label" aria-hidden="true")
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        %button.close(data-dismiss="modal")
          %span(aria-hidden="true")
            &times;
          %span.sr-only Close
        %h2.modal-title#privacy-label= t('privacy.title')
      .modal-body
        = markdown(t('privacy.content')).html_safe
      .modal-footer
        %button.btn.btn-primary(data-dismiss="modal") Schließen

app/views/sellers/resend_activation.html.haml
- content_for :title, t('.title')
.alert.alert-warning= markdown(t('outlook')).html_safe

%p Mit Abschluss Ihrer Registrierung wurde eine eMail an Sie mit der Registrierungsbestätigung und den Zugangsinformationen zu Ihre geschützten Bereich an die von Ihnen bei der Registrierung angegeben eMail-Adresse geschickt.
%p Bitte prüfen Sie zunächst noch einmal, ob die eMail mittlerweile angekommen ist. Prüfen Sie auch den SPAM-Ordner in Ihrem Mailprogramm.
%p Sollten Sie diese eMail auch nach Ablauf einer Stunde noch nicht in Ihrem Mailprogramm finden, können Sie sich diese nochmals zusenden lassen. Geben Sie dazu bitte hier die eMail-Adresse an, die Sie bei der Registrierung verwendet haben.

- if flash[:alert]
  .alert.alert-danger= flash[:alert]

= simple_form_for(@seller, url: resend_activation_seller_path) do |f|
  .form-inputs
    = f.input :email
  .form-actions
    = f.button :submit, t('.resend')

app/views/sellers/show.html.haml
- content_for :title, t('.title')
%p
  Von hier aus können Sie Ihre Stammdaten und Artikel verwalten.
  Sollten Sie keine weitere eMail-Benachrichtigung erhalten oder Ihre Daten löschen wollen,
  können Sie dies in der Stammdatenbearbeitung durchführen.
%h3 Reservierungen
- if @seller.reservations.recent.any?
  %p Sie haben die folgenden Reservierungen:
  %ul
    - @seller.reservations.recent.each do |reservation|
      %li
        %p
          %strong= reservation.event.name
          (#{shopping_time(reservation.event)})<br/>
          - if reservation.event.past?
            Der Flohmarkt ist beendet.
            Sie können sich #{ link_to 'die Ergebnisse', reservation.event } des Flohmarkts anschauen.
            - unless reservation.event.reviewed_by? @seller
              Wir würden uns auch freuen, wenn Sie den #{ link_to 'Flohmarkt bewerten', new_event_reservation_review_path(reservation.event, reservation) } würden.
          - else
            - if reservation.event.commissioned? && reservation.event.reservation_end.future?
              Alle zu verkaufenden Artikel müssen bis zum #{l(reservation.event.reservation_end, format: :long)} eingetragen und die Etiketten erzeugt sein.
            Sie haben bisher #{ reservation.items.count } Artikel angelegt.
            Sie haben die Reservierungsnummer <strong>#{reservation.number}</strong>.<br/>
            - if reservation.event.reservation_end.future?
              Sollten Sie nicht mehr als Verkäufer am Flohmarkt teilnehmen können, bitte geben Sie Ihre Reservierung wieder frei.
            %br
            = link_to 'Artikel bearbeiten', event_reservation_items_path(reservation.event, reservation), type: :primary, icon: :list
            = destroy_link_to(event_reservation_path(reservation.event, reservation), name: 'Reservierung freigeben', icon: :remove_circle, message: t('.confirm_delete_reservation')) if reservation.event.reservation_end.future?
= render '/confirm', locals: { type: :danger }
- if @events
  %h3 Aktuelle Termine
  %p Die folgenden Termine sind aktuell in der Reservierungsphase:
  %ul
    - @events.each do |event|
      %li
        %p
          %strong= event.name
          (#{shopping_time(event)})
          %br
          #{event.reservations_left} von #{event.max_reservations} Plätzen frei
          %br
          - if event.reservable_by?(@seller)
            Sie können eine Reservierungsanfrage stellen.
            %br
            = link_to 'Reservierungsanfrage stellen', event_reservations_path(event), method: :post, type: :primary, icon: :ok_circle
          - elsif @seller.suspended_for?(event)
            Sie können aufgrund einer Sperre keine Reservierung durchführen. Grund der Sperre:
            = @seller.suspensions.find_by(event: event).reason
          - elsif !event.reservations_left?
            Leider sind alle Plätze bereits vergeben.
            - if @seller.notifications.any? { |notification| notification.event == event }
              Sie stehen auf der Warteliste an Position #{waiting_list_position(event, @seller)}.
              = link_to 'Von Warteliste entfernen', event_notification_path(event), method: :delete, type: :warning, icon: :remove_circle
            - elsif event.notifiable_by?(@seller)
              Sie können sich #{ link_to 'auf die Warteliste setzen lassen', event_notification_path(event), method: :post }.
              Sie erhalten eine Mail, sobald ein Platz für Sie frei geworden ist.
          - elsif event.client.reservation_by_seller_forbidden
            Um eine Reservierung zu erhalten,
            =mail_to(current_client.mail_address, 'kontaktieren Sie uns')
            bitte.
          - elsif @seller.notifications.any? { |notification| notification.event == event }
            Ihre Reservierungsanfrage wird verarbeitet.
          - else
            Sie haben bereits die maximale Anzahl erlaubter Reservierungen für diesen Termin.
- unless @events_with_support.empty?
  %h3 Helfer
  %p Bei den folgenden Terminen werden Helfer benötigt:
  %ul
    - @events_with_support.each do |event|
      %li
        = link_to "#{event.name} (#{shopping_time(event)})", event_support_path(event)

%h3 Ihre Stammdaten
%p
  %strong #{@seller.first_name} #{@seller.last_name}<br/>
  #{@seller.street}<br/>
  #{@seller.zip_code} #{@seller.city}<br/>
%p
  Tel.: #{@seller.phone}<br/>
  Mail: #{mail_to @seller.email}
= link_to 'Stammdaten bearbeiten', edit_seller_path, type: :primary, icon: :user